version: '3.8'

services:
  node-app:
    depends_on:
      - postgres-app
    build:
      context: ./
      dockerfile: dockerfile
      target: development
    command: yarn start:dev
    image: node:16.14.0-alpine3.14
    container_name: node-app
    restart: always
    tty: true
    ports:
      - 3333:${APP_PORT}
    volumes:
      - '.:/src/app'
    working_dir: /src/app
    environment:
      - TZ=America/Sao_Paulo

    networks:
      - node-app-network

  postgres:
    image: postgres:9.6
    container_name: postgres-app
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:${POSTGRES_PORT}
    networks:
      - node-app-network

networks:
  node-app-network:
    driver: bridge
